version: '2.3'

volumes:
  mongodata: {}
  uploaddata: {}
  logsdata: {}

networks:
  apinet:
    driver: bridge

services:
  mongodb:
    image: telkomindonesia/alpine:mongodb-3.6
    networks:
      - apinet
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=user
      - MONGODB_PASSWORD=password
      - MONGODB_ADMIN_PASSWORD=password
      - MONGODB_DATABASE=codebase-api
    volumes:
      - mongodata:/var/lib/mongodb/data
    restart: always
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)' || exit 1"] 
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3

  codebase-api:
    build: .
    image: aassuhendar/codebase-api:latest
    networks:
      - apinet
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
      - NODE_SERVER_PORT=3000
      - DB_DRIVER=mongo
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=codebase-api
    restart: always
    volumes:
      - uploaddata:/usr/src/app/uploaded
      - logsdata:/usr/src/app/logs
    # depends_on:
    #   mongodb:
    #     condition: service_healthy